workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 16.4
      cocoapods: default
      vars:
        APP_NAME: "Sal7ly"
    scripts:
      - name: Clean project
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          if [ ! -f "Podfile" ]; then
            echo "platform :ios, '14.0'" > Podfile
          fi
          pod install
          cd ..
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/**/*.ipa
      - build/ios/iphoneos/**/*.app
    publishing:
      email:
        recipients:
          - sameh.dm63@gmail.com
